version: '3.7'

services:
   web:
      build: web
      restart: always
      ports:
         - 8000:8000
      command: gunicorn sitio_web.wsgi:aplicacion --bind 0.0.0.0:8000
      volumes:
         - ./web:/web
   nginx:
      image: nginx:alpine
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./conf:/etc/nginx/conf.d:ro
         - ./web/static:/var/www/static
      depends_on:
         - web
